'use client'

import { useMemo, useState } from 'react'
import { api } from '@/trpc/react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  ArrowLeft,
  Sparkles,
  TrendingUp,
  TrendingDown,
  Calendar,
  Clock,
  Target,
  Lightbulb,
  BarChart3,
  FileText,
  AlertCircle,
  RefreshCw,
  ChevronRight,
  Star,
  Zap,
} from 'lucide-react'
import Link from 'next/link'
import { useInsights, PlatformToggle } from '@/components/insights'

type FocusArea = 'growth' | 'engagement' | 'reach'
type ActiveTab = 'strategic' | 'report' | 'recommendations'

export default function AIAnalysisPage() {
  const { platform } = useInsights()
  const [activeTab, setActiveTab] = useState<ActiveTab>('strategic')
  const [focusArea, setFocusArea] = useState<FocusArea>('engagement')
  const [reportMonth, setReportMonth] = useState(() => {
    const now = new Date()
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`
  })

  // Connection status
  const { data: oauthStatus } = api.metaAuth.getConnectionStatus.useQuery()
  const isConnected = oauthStatus?.connected ?? false

  // Parse report month
  const { month, year } = useMemo(() => {
    const [y, m] = reportMonth.split('-')
    return { month: parseInt(m ?? '1'), year: parseInt(y ?? '2025') }
  }, [reportMonth])

  // AI Queries
  const {
    data: strategicAdvice,
    isLoading: strategicLoading,
    refetch: refetchStrategic,
  } = api.aiAnalysis.getStrategicAdvice.useQuery(
    { platform, focus: focusArea, days: 30 },
    { enabled: isConnected && activeTab === 'strategic' }
  )

  const {
    data: narrativeReport,
    isLoading: reportLoading,
    refetch: refetchReport,
  } = api.aiAnalysis.generateNarrativeReport.useQuery(
    { platform, month, year },
    { enabled: isConnected && activeTab === 'report' }
  )

  const {
    data: postingRecs,
    isLoading: recsLoading,
    refetch: refetchRecs,
  } = api.aiAnalysis.getPostingRecommendations.useQuery(
    { platform, days: 30 },
    { enabled: isConnected && activeTab === 'recommendations' }
  )

  // Not connected state
  if (!isConnected) {
    return (
      <div className="space-y-6">
        <Header />
        <Card className="border-amber-200 bg-amber-50">
          <CardContent className="flex items-center gap-4 pt-6">
            <AlertCircle className="h-8 w-8 text-amber-600" />
            <div className="flex-1">
              <h3 className="font-semibold text-amber-800">Meta API Not Connected</h3>
              <p className="text-sm text-amber-700">Connect your accounts to use AI analysis.</p>
            </div>
            <Button asChild>
              <Link href="/admin/settings/connections">Configure Connection</Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <Header />

      {/* Intro Card */}
      <Card className="bg-gradient-to-r from-purple-50 to-blue-50 dark:from-purple-950/30 dark:to-blue-950/30 border-purple-200 dark:border-purple-800">
        <CardContent className="flex items-start gap-4 pt-6">
          <div className="p-3 rounded-full bg-purple-100 dark:bg-purple-900">
            <Sparkles className="h-6 w-6 text-purple-600 dark:text-purple-400" />
          </div>
          <div className="flex-1">
            <h3 className="font-semibold text-purple-900 dark:text-purple-100 mb-1">
              Claude AI Analysis
            </h3>
            <p className="text-sm text-purple-700 dark:text-purple-300">
              Get AI-powered insights, strategic recommendations, and performance analysis based on
              your social media data. All analysis is generated by Claude and tailored to your
              specific content and metrics.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as ActiveTab)}>
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="strategic" className="gap-2">
            <Target className="h-4 w-4" />
            <span className="hidden sm:inline">Strategic Advice</span>
            <span className="sm:hidden">Strategy</span>
          </TabsTrigger>
          <TabsTrigger value="report" className="gap-2">
            <FileText className="h-4 w-4" />
            <span className="hidden sm:inline">Monthly Report</span>
            <span className="sm:hidden">Report</span>
          </TabsTrigger>
          <TabsTrigger value="recommendations" className="gap-2">
            <Lightbulb className="h-4 w-4" />
            <span className="hidden sm:inline">Posting Tips</span>
            <span className="sm:hidden">Tips</span>
          </TabsTrigger>
        </TabsList>

        {/* Strategic Advice Tab */}
        <TabsContent value="strategic" className="space-y-6 mt-6">
          {/* Focus Selector */}
          <div className="flex flex-wrap items-center gap-4">
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">Focus on:</span>
              <Select value={focusArea} onValueChange={(v) => setFocusArea(v as FocusArea)}>
                <SelectTrigger className="w-40">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="growth">
                    <div className="flex items-center gap-2">
                      <TrendingUp className="h-4 w-4 text-green-500" />
                      Growth
                    </div>
                  </SelectItem>
                  <SelectItem value="engagement">
                    <div className="flex items-center gap-2">
                      <Zap className="h-4 w-4 text-amber-500" />
                      Engagement
                    </div>
                  </SelectItem>
                  <SelectItem value="reach">
                    <div className="flex items-center gap-2">
                      <Target className="h-4 w-4 text-blue-500" />
                      Reach
                    </div>
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button variant="outline" size="sm" onClick={() => refetchStrategic()}>
              <RefreshCw className="h-4 w-4 mr-2" />
              Refresh
            </Button>
          </div>

          {strategicLoading ? (
            <LoadingState message="Generating strategic advice..." />
          ) : strategicAdvice ? (
            <div className="grid gap-6">
              {/* Summary */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Sparkles className="h-5 w-5 text-purple-500" />
                    Strategic Summary
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm leading-relaxed">{strategicAdvice.summary}</p>
                </CardContent>
              </Card>

              {/* Top Opportunities */}
              {strategicAdvice.topOpportunities && strategicAdvice.topOpportunities.length > 0 && (
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <Star className="h-5 w-5 text-yellow-500" />
                      Top Opportunities
                    </CardTitle>
                    <CardDescription>
                      Actionable recommendations to improve performance
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      {strategicAdvice.topOpportunities.map((opp, i) => (
                        <div key={i} className="p-4 bg-muted/50 rounded-lg space-y-2">
                          <div className="flex items-start justify-between gap-2">
                            <h4 className="font-medium">{opp.title}</h4>
                            <EffortBadge effort={opp.effort} />
                          </div>
                          <p className="text-sm text-muted-foreground">{opp.description}</p>
                          <div className="flex items-center gap-2 text-sm">
                            <TrendingUp className="h-4 w-4 text-green-500" />
                            <span className="text-green-600 dark:text-green-400">
                              {opp.expectedImpact}
                            </span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              )}

              {/* Content Calendar Suggestions */}
              {strategicAdvice.contentCalendarSuggestions &&
                strategicAdvice.contentCalendarSuggestions.length > 0 && (
                  <Card>
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <Calendar className="h-5 w-5 text-blue-500" />
                        Content Calendar Suggestions
                      </CardTitle>
                      <CardDescription>Optimal content schedule based on your data</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                        {strategicAdvice.contentCalendarSuggestions.map((sug, i) => (
                          <div
                            key={i}
                            className="p-3 bg-muted/50 rounded-lg border border-transparent hover:border-primary/20 transition-colors"
                          >
                            <div className="font-medium text-sm mb-1">{sug.dayOfWeek}</div>
                            <div className="text-xs text-muted-foreground space-y-1">
                              <div className="flex items-center gap-1">
                                <BarChart3 className="h-3 w-3" />
                                {sug.contentType}
                              </div>
                              <div className="flex items-center gap-1">
                                <ChevronRight className="h-3 w-3" />
                                {sug.theme}
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                )}

              {/* Competitor Insights */}
              {strategicAdvice.competitorInsights &&
                strategicAdvice.competitorInsights.length > 0 && (
                  <Card>
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <Target className="h-5 w-5 text-purple-500" />
                        Competitor Insights
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <ul className="space-y-2">
                        {strategicAdvice.competitorInsights.map((insight, i) => (
                          <li key={i} className="flex items-start gap-2 text-sm">
                            <span className="text-purple-500 mt-0.5">★</span>
                            <span>{insight}</span>
                          </li>
                        ))}
                      </ul>
                    </CardContent>
                  </Card>
                )}
            </div>
          ) : (
            <EmptyState message="Unable to generate strategic advice. Make sure you have content synced." />
          )}
        </TabsContent>

        {/* Monthly Report Tab */}
        <TabsContent value="report" className="space-y-6 mt-6">
          {/* Month Selector */}
          <div className="flex flex-wrap items-center gap-4">
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">Report for:</span>
              <input
                type="month"
                value={reportMonth}
                onChange={(e) => setReportMonth(e.target.value)}
                className="px-3 py-2 border rounded-md text-sm bg-background"
              />
            </div>
            <Button variant="outline" size="sm" onClick={() => refetchReport()}>
              <RefreshCw className="h-4 w-4 mr-2" />
              Regenerate
            </Button>
          </div>

          {reportLoading ? (
            <LoadingState message="Generating monthly report..." />
          ) : narrativeReport ? (
            <div className="grid gap-6">
              {/* Summary */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <FileText className="h-5 w-5 text-blue-500" />
                    {getMonthName(month)} {year} Performance Summary
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm leading-relaxed">{narrativeReport.summary}</p>
                </CardContent>
              </Card>

              {/* Highlights */}
              {narrativeReport.highlights && narrativeReport.highlights.length > 0 && (
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <Star className="h-5 w-5 text-yellow-500" />
                      Highlights
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                      {narrativeReport.highlights.map((highlight, i) => (
                        <div key={i} className="p-4 bg-muted/50 rounded-lg">
                          <h4 className="font-medium text-sm mb-1">{highlight.title}</h4>
                          <div className="text-2xl font-bold mb-1">{highlight.metric}</div>
                          <p className="text-xs text-muted-foreground">{highlight.context}</p>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              )}

              {/* Challenges */}
              {narrativeReport.challenges && narrativeReport.challenges.length > 0 && (
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <TrendingDown className="h-5 w-5 text-red-500" />
                      Challenges
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-2">
                      {narrativeReport.challenges.map((challenge, i) => (
                        <li key={i} className="flex items-start gap-2 text-sm">
                          <span className="text-red-500 mt-0.5">•</span>
                          <span>{challenge}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              )}

              {/* Recommendations */}
              {narrativeReport.recommendations && narrativeReport.recommendations.length > 0 && (
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <Lightbulb className="h-5 w-5 text-amber-500" />
                      Recommendations
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-2">
                      {narrativeReport.recommendations.map((rec, i) => (
                        <li key={i} className="flex items-start gap-2 text-sm">
                          <span className="text-amber-500 mt-0.5">→</span>
                          <span>{rec}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              )}

              {/* Outlook */}
              {narrativeReport.outlook && (
                <Card className="bg-gradient-to-r from-green-50 to-blue-50 dark:from-green-950/30 dark:to-blue-950/30">
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <TrendingUp className="h-5 w-5 text-green-500" />
                      Outlook
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm leading-relaxed">{narrativeReport.outlook}</p>
                  </CardContent>
                </Card>
              )}
            </div>
          ) : (
            <EmptyState message="Unable to generate report. Make sure you have data for the selected month." />
          )}
        </TabsContent>

        {/* Posting Recommendations Tab */}
        <TabsContent value="recommendations" className="space-y-6 mt-6">
          <div className="flex justify-end">
            <Button variant="outline" size="sm" onClick={() => refetchRecs()}>
              <RefreshCw className="h-4 w-4 mr-2" />
              Refresh
            </Button>
          </div>

          {recsLoading ? (
            <LoadingState message="Analyzing posting patterns..." />
          ) : postingRecs ? (
            <div className="grid gap-6 lg:grid-cols-2">
              {/* Best Posting Time */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Clock className="h-5 w-5 text-blue-500" />
                    Best Posting Time
                  </CardTitle>
                  <CardDescription>When your audience is most active</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="text-center py-4">
                    <div className="text-4xl font-bold text-blue-600 dark:text-blue-400">
                      {postingRecs.bestPostingTime.dayOfWeek}
                    </div>
                    <div className="text-2xl font-semibold mt-2">
                      {formatHour(postingRecs.bestPostingTime.hour)}
                    </div>
                    <div className="text-sm text-muted-foreground mt-1">
                      {postingRecs.bestPostingTime.timezone}
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Optimal Content Type */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <BarChart3 className="h-5 w-5 text-purple-500" />
                    Optimal Content Type
                  </CardTitle>
                  <CardDescription>Content format that performs best</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="text-center py-4">
                    <div className="text-4xl font-bold text-purple-600 dark:text-purple-400">
                      {postingRecs.optimalContentType}
                    </div>
                    <div className="mt-4 flex items-center justify-center gap-2">
                      <Badge variant="outline">
                        {Math.round(postingRecs.confidence * 100)}% confidence
                      </Badge>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Engagement Prediction */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Target className="h-5 w-5 text-green-500" />
                    Engagement Prediction
                  </CardTitle>
                  <CardDescription>Expected engagement for your next post</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="text-center py-4">
                    <div className="text-4xl font-bold text-green-600 dark:text-green-400">
                      {postingRecs.engagementPrediction.toLocaleString()}
                    </div>
                    <div className="text-sm text-muted-foreground mt-1">estimated interactions</div>
                    <p className="text-xs text-muted-foreground mt-3">
                      Based on optimal time + content type
                    </p>
                  </div>
                </CardContent>
              </Card>

              {/* Suggested Hashtags */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Sparkles className="h-5 w-5 text-amber-500" />
                    Suggested Hashtags
                  </CardTitle>
                  <CardDescription>High-performing tags for your niche</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2">
                    {postingRecs.suggestedHashtags.map((tag, i) => (
                      <Badge key={i} variant="secondary" className="text-sm">
                        #{tag}
                      </Badge>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </div>
          ) : (
            <EmptyState message="Unable to generate recommendations. Make sure you have content synced." />
          )}
        </TabsContent>
      </Tabs>

      {/* Quick Links */}
      <Card>
        <CardHeader>
          <CardTitle className="text-sm font-medium">Related Pages</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-2">
            <Button variant="outline" size="sm" asChild>
              <Link href="/admin/insights/content">
                <BarChart3 className="h-4 w-4 mr-2" />
                Content Hub
              </Link>
            </Button>
            <Button variant="outline" size="sm" asChild>
              <Link href="/admin/insights/content/compare">
                <Target className="h-4 w-4 mr-2" />
                Compare Posts
              </Link>
            </Button>
            <Button variant="outline" size="sm" asChild>
              <Link href="/admin/insights">
                <ChevronRight className="h-4 w-4 mr-2" />
                Overview
              </Link>
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

function Header() {
  return (
    <div className="sticky top-0 z-10 -mx-6 -mt-6 mb-6 bg-background/95 px-6 py-4 backdrop-blur supports-[backdrop-filter]:bg-background/60 border-b">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="sm" asChild>
            <Link href="/admin/insights">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back
            </Link>
          </Button>
          <div>
            <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
              <Sparkles className="h-8 w-8 text-purple-500" />
              AI Analysis
            </h1>
            <p className="text-muted-foreground">Claude-powered insights and recommendations</p>
          </div>
        </div>
        <PlatformToggle />
      </div>
    </div>
  )
}

function LoadingState({ message }: { message: string }) {
  return (
    <Card>
      <CardContent className="py-12">
        <div className="flex flex-col items-center gap-4">
          <Sparkles className="h-8 w-8 text-purple-500 animate-pulse" />
          <p className="text-sm text-muted-foreground">{message}</p>
          <div className="w-full max-w-md space-y-3">
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-3/4" />
            <Skeleton className="h-4 w-5/6" />
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

function EmptyState({ message }: { message: string }) {
  return (
    <Card>
      <CardContent className="py-12">
        <div className="flex flex-col items-center gap-4">
          <AlertCircle className="h-8 w-8 text-muted-foreground" />
          <p className="text-sm text-muted-foreground text-center max-w-md">{message}</p>
        </div>
      </CardContent>
    </Card>
  )
}

function EffortBadge({ effort }: { effort: 'low' | 'medium' | 'high' }) {
  const colors = {
    low: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
    medium: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400',
    high: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
  }

  return (
    <Badge variant="outline" className={colors[effort]}>
      {effort} effort
    </Badge>
  )
}

function getMonthName(month: number): string {
  const months = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ]
  return months[month - 1] ?? 'Unknown'
}

function formatHour(hour: number): string {
  const suffix = hour >= 12 ? 'PM' : 'AM'
  const displayHour = hour % 12 || 12
  return `${displayHour}:00 ${suffix}`
}
